# Generated by Django 5.2 on 2025-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0005_rename_lyrics_chartsong_lylics"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="agency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="album_cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="emotion_tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="genius_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
