# Generated by Django 5.2 on 2025-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0006_chartsong_agency_chartsong_album_cover_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartsong",
            name="agency",
        ),
        migrations.RemoveField(
            model_name="chartsong",
            name="label",
        ),
        migrations.AlterField(
            model_name="chartsong",
            name="genius_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
