# Generated by Django 5.2 on 2025-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyricsgen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlyrics",
            name="language",
            field=models.CharField(default="none", max_length=20),
        ),
    ]
